name: Container Image

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  create-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Update versions
        id: update
        run: |
          archi_version=$(curl -fsSL https://api.github.com/repos/archimatetool/archi/tags | jq -r '.[0].name | ltrimstr("release_")')
          sed -i "s/^\(ARCHI_VERSION=\).*/\1$archi_version/" versions

          coarchi_version=$(curl -fsSL https://api.github.com/repos/archimatetool/archi-modelrepository-plugin/tags | jq -r '.[0].name | ltrimstr("v")')
          sed -i "s/^\(COARCHI_VERSION=\).*/\1$coarchi_version/" versions

          if git diff --quiet -- versions; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "changed=true" >> "$GITHUB_OUTPUT"
          echo "version=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
          echo -e "versions<<EOF\n$(cat versions)\nEOF" >> "$GITHUB_OUTPUT"

      - name: Download and extract Archi and plugins
        if: steps.update.outputs.changed == 'true'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y libarchive-tools
          source ./versions
          mkdir -p build/plugins

          wget -O - -q "https://github.com/archimatetool/archi.io/releases/download/${ARCHI_VERSION//./_}/Archi-Linux64-${ARCHI_VERSION}.tgz" \
            | bsdtar -xf - -C build/ --strip-components=1

          wget -O - -q "https://www.archimatetool.com/downloads/coarchi/coArchi_${COARCHI_VERSION}.archiplugin" \
            | bsdtar -xf - -C build/plugins

      - uses: docker/login-action@v4
        if: steps.update.outputs.changed == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v7
        if: steps.update.outputs.changed == 'true'
        with:
          context: .
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.update.outputs.version }}
          push: true

      - name: Commit and push
        if: steps.update.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add versions
          git commit -m "chore: update versions"
          git tag -a "${{ steps.update.outputs.version }}" -m $'Version: ${{ steps.update.outputs.version }}\n\n${{ steps.update.outputs.versions }}'
          git push --atomic origin "${{ github.ref_name }}" "${{ steps.update.outputs.version }}"