name: Publish image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get versions
        id: versions
        run: |
          VERSIONS=$(tr '\n' ',' < versions | sed 's/,$//')
          echo "list=$VERSIONS" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          build-args: ${{ steps.versions.outputs.list }}
          tags: archi:latest,archi:${{ github.ref_name }},archi:${{ github.event.inputs.tag }}
          push: true
